name: Deploy Functions (remote build via publish-profile)

on:
  push:
    branches: [ main ]
    paths:
      - 'app/**'
      - '.github/workflows/deploy-functions.yml'

permissions:
  contents: read

env:
  AZURE_FUNCTIONAPP_NAME: "reco-func-43896"
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "app"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: p10
    steps:
      - uses: actions/checkout@v4

      # ⚠️ Pas d'installation pip côté CI !
      - name: Ensure no local .python_packages
        run: rm -rf "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/.python_packages" || true

      - name: Deploy (zipDeploy + Kudu/Oryx)
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          enable-oryx-build: true
          scm-do-build-during-deployment: true
          respect-funcignore: true
