name: Deploy Azure Functions (Python v2 via OIDC)

on:
  push:
    branches: [ main ]

permissions:
  id-token: write    # requis pour OIDC
  contents: read

env:
  AZURE_FUNCTIONAPP_NAME: reco-func-43896
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "./app"   # dossier qui contient function_app.py

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Python (optional for tests/lint)
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          enable-oryx-build: true
          scm-do-build-during-deployment: true
